### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by worlddeleteRin** [szboynono/mosha-vue-toastify#8]
Toast took almost full width on mobile (iphone 6,7,8). Have a propose to include such styles to the `.mosha__toast` class out of the box:
```css
.mosha__toast {
       width: 85%;
       max-width: 400px;
       margin-right: 9px;
   }
```
